# Optimizer Functions

################################################################################
#
# CONFIDENTIAL, NOT FOR DISTRIBUTION
#
################################################################################

# Copyright 2006-2008 Brian G. Peterson, Peter Carl, Ktris Boudt
# $Id: optimizer.R,v 1.38 2008-01-20 17:22:15 brian Exp $

################################################################################
# FUNCTIONS:
#
# BruteForcePortfolios (R,weightgrid,yeargrid)
# BacktestData ()
# Backtest (R,portfolioreturns, yeargrid, cutat=1000000, methods, p, ... )
# weight.grid (columnnames, seqstart=.05, seqend=.25, seqstep=.05)
# maxdrawdown (R)
# cut.returns (R, cutrow, startrow=1)
# weighttest (weightgrid, test=1)
# WeightedReturns (R, weightgrid, from, to, methods, p, ...)
# backtestDisplay (R, portfolioreturns, yeargrid, backtestresults, show="Cumulative.Return" )
# MonthlyBacktestResults (R, weightgrid, yeargrid, backtestweights)
#
################################################################################

# Check to see if the required libraries are loaded
if(!require("PerformanceAnalytics", quietly=TRUE)) {
    stop("package", sQuote("PerformanceAnalytics"), "is needed.  Stopping")
}
source("optim_functions.R")

# ------------------------------------------------------------------------------
cut.returns =
function (R, cutrow, startrow=1)
{   # @author Brian G. Peterson

    # Description:

    # FUNCTION:
    result = R[startrow:cutrow,]

    # Return Value:
    result
}

# ------------------------------------------------------------------------------
weighttest =
function (weightgrid, test=1)
{
    rows=nrow(weightgrid)

    result=NA

    for(row in 1:rows) {
        r = as.vector(weightgrid[row,])
        #if (!is.numeric(r)) stop("The selected row is not numeric")

        if (sum(r) == test) {
            #if (result=NA) {
                #create data.frame
            #    result=data.frame(r=r)
            #} else {
                r=data.frame(r=r)
                result=cbind(result,r)
            #}
        }
    } #end rows loop

    # Return Value:
    result

}

# ------------------------------------------------------------------------------
# @todo: replace pfolioReturn(returnarray,weightingvector) from fPortfolio
#        use updated Return.cumulative
# @todo: use zoo rollapply in BruteForcePortfolios() fn
#WeightedReturns =
WeightedReturns =
function (R, weightgrid, from, to,
          methods=c( "PeriodGVaR", "ThreeYrGVaR", "InceptionGVaR", "PeriodmodVaR", "ThreeYrmodVaR", "InceptionmodVaR",
                     "PeriodGES", "ThreeYrGES", "InceptionGES", "PeriodmodES", "ThreeYrmodES", "InceptionmodES",
                     "maxdd", "omega", "PeriodStdDev", "ThreeYrStdDev", "InceptionStdDev" )
          , p=0.95, ... )
{ # @author Brian G. Peterson and Kris Boudt

    # Description:
    # This is the workhorse of the backtest architecture.
    # Any optimization backtesting model must
    #     - create portfolios,
    #     - analyze their returns,
    #     - and allow you to use some metric, function, or algorithm
    #       to analyze the results
    #
    # function takes a set of returns, a set of portfolio weights,
    # and a timeframe to operate within, and generates a set of statistics
    # for every possible weight.
    #
    # When you calculate statistics for all possible weights generated by
    # a brute force method, an estimation method, some function,
    # a regression, etc., you can then run tests against the results "in-sample"
    # to determine which weighting vector you want to use "out-of-sample"
    # in the next rolling period.
    #
    # This function is extremely computationally intensive, because it is doing
    # a lot of things with every single possible weighting vector, so you want
    # to be able to run it and store the results for later analysis.
    # It is best to strike a balance between placing functions in here that
    # you will need to help choose the optimal weighting vector, and be
    # parsimonious, as these calculations may be run tens of thousands of times
    # in any given backtest.  Remember that once you have chosen an optimal
    # portfolio or a sub-set of possible optimal portfolios, you can run more
    # exhaustive analytics on each of your candidates later, rather than on the
    # entire set of all possible portfolios.
    #
    # R             data structure of historical returns
    # weightgrid    each row contains one weighting vector, same number of columns as your returns
    # from          where to cut the beginning of the return stream
    # to            where to cut the end of the return stream
    #
    # @returns      data frame where each row has the same index number as a weighting vector,
    #               and each column is one of your metrics from inside this function
    #
    # @todo don't recalculate if Period and ThreeYr or Inception and ThreeYr are the same

    # Setup:
    rows=nrow(weightgrid)

    if (from < 1) from = 1
    if (to > rows) to = rows

    # data type conditionals
    # cut the return series for from:to
    if (class(R) == "timeSeries") {
        R = R@Data
    }
    # should probably change this part to use zoo's rollapply to create the various groupings

    if (ncol(weightgrid) != ncol(R)) stop ("The Weighting Vector and Return Collection do not have the same number of Columns.")

    result=data.frame()

    # Compute multivariate moments

    threeyrfrom = to - 36; #for monthly data
    if (threeyrfrom < 1 ) threeyrfrom = 1

    R.inception = R[1:to , ];
    mu.inception = apply(R.inception,2,'mean');
    sigma.inception = cov(R.inception);
    M3.inception = M3.MM(R.inception);
    M4.inception = M4.MM(R.inception);

    R.period = R[from:to, ];
    mu.period =  apply(R.period,2,'mean');
    sigma.period = cov(R.period);
    M3.period = M3.MM(R.period);
    M4.period = M4.MM(R.period);

    R.3yr = R[ threeyrfrom:to, ];
    mu.3yr = apply(R.3yr,2,'mean');
    sigma.3yr = cov(R.3yr);
    M3.3yr = M3.MM(R.3yr);
    M4.3yr = M4.MM(R.3yr);

    # Function:
    for(row in 1:rows) {
        # at some point consider parallelizing this by using a clustered apply
        # to call a sub-function so that this could get distributed
        # to multiple processor cores or threads

        w = as.numeric(weightgrid[row,])
        # test each row in the weighting vectors against the right dates in the return collection

        # construct a data structure that holds each result for this row
        resultrow=data.frame(row.names = row)

       # problem of NAs? Not solved yet !!!!
       # should really solve this by calling checkData in ButeForcePortfolios
       #if (any(is.na(R))) {
       #     print( paste("NA\'s in returns: ",row, " ",w," from ", from) )
       #     #browser()
       #}

        mean.inception = mean.MM( w , mu.inception );
        mean.period = mean.MM( w , mu.period) ;
        mean.3yr = mean.MM( w , mu.3yr ) ;

        for (method in methods) {
            switch(method,
                PeriodStdDev = {
                    # Standard Deviation
                    PeriodStdDev = StdDev.MM(w,sigma=sigma.period)
                    PeriodSRStdDev = mean.period/ PeriodStdDev
                    colnames(PeriodStdDev) = "StdDev.period"
                    colnames(PeriodSRStdDev)="SR.StdDev.period"
                    resultrow= cbind(resultrow,PeriodStdDev,PeriodSRStdDev)
                },
                ThreeYrStdDev = {
                    # Standard Deviation
                    ThreeYrStdDev = StdDev.MM(w,sigma=sigma.3yr)
                    ThreeYrSRStdDev = mean.3yr/ThreeYrStdDev;
                    colnames(PeriodStdDev) = "StdDev.3yr"
                    colnames(ThreeYrStdDev) = "SR.StdDev.3yr"
                    resultrow= cbind(resultrow,ThreeYrStdDev,ThreeYrSRStdDev)
                },
                InceptionStdDev = {
                    # Standard Deviation
                    InceptionStdDev = StdDev.MM(w,sigma=sigma.inception)
                    InceptionSRStdDev = mean.inception/InceptionStdDev
                    colnames(InceptionStdDev) = "StdDev.inception"
                    colnames(InceptionSRStdDev) = "SR.StdDev.inception"
                    resultrow= cbind(resultrow,InceptionStdDev, InceptionSRStdDev)
                },
                PeriodGVaR = {
                    PeriodGVaR = GVaR.MM(w=w, mu=mu.period, sigma = sigma.period, p=p )
                    PeriodSRGVaR = mean.period/PeriodGVaR
                    colnames(PeriodGVaR)="GVaR.period"
                    colnames(PeriodSRGVaR)="SR.GVaR.period"
                    resultrow= cbind(resultrow,PeriodGVaR,PeriodSRGVaR)
                },
                ThreeYrGVaR = {
                    ThreeYrVaR = GVaR.MM(w=w, mu=mu.period, sigma = sigma.period, p=p )
                    ThreeYrSRGVaR =  mean.3yr/ThreeYrGVaR
                    colnames(ThreeYrGVaR)="GVaR.3yr"
                    colnames(ThreeYrSRGVaR)="SR.GVaR.3yr"
                    resultrow= cbind(resultrow,ThreeYrGVaR,ThreeYrSRGVaR)
                },
                InceptionGVaR = {
                    InceptionGVaR = GVaR.MM(w=w, mu=mu.inception, sigma = sigma.inception, p=p )
                    InceptionSRGVaR = mean.inception/InceptionGVaR
                    colnames(InceptionGVaR)="GVaR.inception"
                    colnames(InceptionSRGVaR)="SR.GVaR.inception"
                    resultrow= cbind(resultrow,InceptionGVaR,InceptionSRGVaR)
                },
                PeriodmodVaR = {
                    PeriodmodVaR = mVaR.MM(w=w, mu=mu.period, sigma = sigma.period, M3=M3.period , M4 =M4.period , p=p )
                    PeriodSRmodVaR = mean.period/PeriodmodVaR
                    colnames(PeriodmodVaR)="modVaR.period"
                    colnames(PeriodSRmodVaR)="SR.modVaR.period"
                    resultrow= cbind(resultrow,PeriodmodVaR,PeriodSRmodVaR)
                },
                InceptionmodVaR = {
                    InceptionmodVaR = mVaR.MM(w=w, mu=mu.inception, sigma = sigma.inception, M3=M3.inception , M4 =M4.inception , p=p )
                    InceptionSRmodVaR = mean.inception/InceptionmodVaR
                    colnames(InceptionmodVaR)="modVaR.inception"
                    colnames(InceptionSRmodVaR)="SR.modVaR.inception"
                    resultrow= cbind(resultrow,InceptionmodVaR,InceptionSRmodVaR)
                },
                ThreeYrmodVaR = {
                    ThreeYrmodVaR = mVaR.MM(w=w, mu=mu.period, sigma = sigma.3yr, M3=M3.3yr , M4 =M4.3yr, p=p )
                    ThreeYrSRmodVaR = mean.3yr/ThreeYrmodVaR
                    colnames(ThreeYrmodVaR)="modVaR.3yr"
                    colnames(ThreeYrSRmodVaR)="SR.modVaR.3yr"
                    resultrow= cbind(resultrow,ThreeYrmodVaR,ThreeYrSRmodVaR)
                },
                InceptionGES = {
                    InceptionGES = GES.MM(w=w, mu=mu.inception, sigma = sigma.inception, p=p )
                    InceptionSRGES = mean.inception/InceptionGES
                    colnames(InceptionGES)="GES.inception"
                    colnames(InceptionSRGES)="SR.GES.inception"
                    resultrow= cbind(resultrow,InceptionGES,InceptionSRGES)
                },
                PeriodGES = {
                    PeriodGES = GES.MM(w=w, mu=mu.period, sigma = sigma.period, p=p )
                    PeriodSRGES =  mean.period/PeriodGES
                    colnames(PeriodGES)="GES.period"
                    colnames(PeriodSRGES)="SR.GES.period"
                    resultrow= cbind(resultrow,PeriodGES,PeriodSRGES)
                },
                ThreeYrGES = {
                    ThreeYrGES = GES.MM(w=w, mu=mu.3yr, sigma = sigma.3yr, p=p )
                    ThreeYrSRGES = mean.3yr/ThreeYrGES
                    colnames(ThreeYrGES)="GES.3yr"
                    colnames(ThreeYrSRGES)="SR.GES.3yr"
                    resultrow= cbind(resultrow,ThreeYrGES,ThreeYrSRGES)
                },
                PeriodmodES = {
                    PeriodmodES = mES.MM(w=w, mu=mu.period, sigma = sigma.period, M3=M3.period , M4 =M4.period , p=p )
                    PeriodSRmodES =  mean.period/PeriodmodES
                    colnames(PeriodmodES)="modES.period"
                    colnames(PeriodSRmodES)="SR.modES.period"
                    resultrow= cbind(resultrow,PeriodmodES,PeriodSRmodES)
                },
                ThreeYrmodES = {
                    ThreeYrmodES = mES.MM(w=w, mu=mu.3yr, sigma = sigma.3yr, M3=M3.3yr , M4 =M4.3yr , p=p )
                    ThreeYrSRmodES = mean.3yr/ThreeYrmodES
                    colnames(ThreeYrmodES)="modES.3yr"
                    colnames(ThreeYrSRmodES)="SR.modES.3yr"
                    resultrow= cbind(resultrow,ThreeYrmodES,ThreeYrSRmodES)
                },
                InceptionmodES = {
                    InceptionmodES = mES.MM(w=w, mu=mu.inception, sigma = sigma.inception, M3=M3.inception , M4 =M4.inception, p=p )
                    InceptionSRmodES = mean.inception/InceptionmodES
                    colnames(InceptionmodES)="modES.inception"
                    colnames(InceptionSRmodES)="SR.modES.inception"
                    resultrow= cbind(resultrow,InceptionmodES,InceptionSRmodES)
                }
            )#end switch function
        }# end loop over methods

        # first cbind the columns
        #resultrow = cbind( cumReturn, ThreeYrMeanReturn, PeriodmodVaR, ThreeYrmodVaR, maxdd,
        #PeriodSharpe, ThreeYrSharpe, omega, StdDev, ThreeYrStdDev )

        rownames(resultrow) = row

        # then rbind the rows
        result    = rbind(result,resultrow)

    } #end rows loop

    # set pretty labels for the columns
    #     colnames(result)=c("Cumulative Return","Mean Return,3 yr","VaR.CornishFisher,period","VaR.CornishFisher,3yr","Max Drawdown",
    #                    "Sharpe,period","Sharpe,3 yr", "Omega", "Std Dev","Std Dev,3yr" )

    # Return Value:
    result

}


# ------------------------------------------------------------------------------
# @todo: use zoo rollapply in BruteForcePortfolios() fn
BruteForcePortfolios =
function(R,weightgrid,yeargrid,
          methods=c( "PeriodGVaR", "ThreeYrGVaR", "InceptionGVaR", "PeriodmodVaR", "ThreeYrmodVaR", "InceptionmodVaR",
                     "PeriodGES", "ThreeYrGES", "InceptionGES", "PeriodmodES", "ThreeYrmodES", "InceptionmodES",
                     "maxdd", "omega", "PeriodStdDev", "ThreeYrStdDev", "InceptionStdDev" )
         , p=0.95, ...
        )
{ # @author Brian G. Peterson

    # Description:
    #
    # Performs the looping and storage of the base analytics for your series
    # of possible portfolios.  I've titled the third parameter 'yeargrid',
    # but it is really a 'rolling window grid', although these will often be years.
    # We slice the computation into these years or rolling periods,
    # and store the results separately, because each of these rolling periods will
    # have one solution for each possible weighting vector.  By generating them and
    # storing them for all weighting vectors in every period, you can do all the hard
    # computational work in one pass, and then reuse the data set over and over again
    # in multiple analytic tests, methods, or hypotheses for choosing in-sample results
    # to use as out-of-sample weights.
    #
    # @todo add optional subdirectory tp keep different backtests apart
    #
    # R                 data frame of historical returns
    #
    # weightgrid        each row contains one weighting vector, same number of columns as your returns
    #
    # yeargrid          list of from/to vectors for the periods we want to backtest over
    #
    # Return:
    # portfolioreturns  list of data frames of set of returns for all possible portfolios
    #                   (output of BruteForcePortfolios function)

    # Setup:
    rows=nrow(yeargrid)

    # Function:
    print( paste("Started:",date()) )
    for (rnum in 1:rows) {
        row = yeargrid[rnum,]
        yearname=rownames(row)
        from = row [,1]
        to   = row [,2]

        if (   1  > from ) from = 1
        if ( rows > to   ) to   = rows

        # construct a data structure that holds each result for this year
        # first cbind
        resultarray = WeightedReturns(R, weightgrid, from, to, methods=methods, p=p, ...=...)

        # then write a CSV
        write.table(resultarray, file = paste(yearname,".csv",sep=""),
            append = FALSE, quote = TRUE, sep = ",",
            eol = "\n", na = "NA", dec = ".", row.names = TRUE,
            col.names = TRUE, qmethod = "escape")

        print( paste("Completed",yearname,":",date()) )
        # print(resultarray)
    }  # end row loop
}

# ------------------------------------------------------------------------------
BacktestData =
function(yeargrid)
{ # @author Brian G. Peterson

    # Description:
    #
    # load the data into a list suitable for use by Backtest and BacktestDisplay functions
    # use the yeargrid used by BruteForcePortfolios to figure out which files to load
    #
    # @todo add optional subdirectory to keep different backtests apart
    #
    # yeargrid          list of from/to vectors for the periods we've run the backtest over
    #                   yeargrid will have one row for the last out of sample year,
    #                   which is not calculated by BruteForcePortfolios

    # Function:
    rows=nrow(yeargrid)-1 # take out the out of sample year, for which there is no data

    for (rnum in 1:rows) {
        row = yeargrid[rnum,]
        yearname=rownames(row)
        # print(yearname)
        currentyeardata  = read.table(paste(yearname,".csv",sep=""),header=TRUE, row.names = 1,sep = ",")
        if (rnum==1) {
            #create e,ty list, as c() doesn't work the way you would expect with a list
            result=vector("list")
        }

        #assign each year into the list using the yearname as the index
        result[[yearname]]=currentyeardata

    }
    names(result) = t(rownames(yeargrid[1:rows,]))

    #Return:
    result
}

# ------------------------------------------------------------------------------
Backtest =
function(R,portfolioreturns, yeargrid, cutat=1000000, benchmarkreturns )
{
    # Description:
    #
    # complete brute force hackjob to get out of sample results
    #
    # Given a set of historical returns R, and a set of portfolio returns calculated from
    # the BruteForcePortfolios function, we can now apply several utility functions to
    # find the best portfolio out of the universe of all sample portfolios.
    #
    # Basically, we find and in-sample solution to each utility function, and store the
    # weighting vector for that portfolio as our strategic weight for use out of sample.
    # by testing several utility functions, we can examine the models for bias, and determine
    # which utility function produces the most acceptable out of sample results.
    #
    # R                 data frame of historical returns
    #
    # portfolioreturns  list of data frames of set of returns for all possible portfolios
    #                   (output of BruteForcePortfolios function)
    #
    # yeargrid          list of from/to vectors for the periods we want to backtest over
    #
    # cutat             numerical index to stop comparing the portfolioreturns at.
    #                   used to slice the weighted returns at particular weight
    #
    # benchmarkreturns  return vector for benchmark, should match the dates on
    #                   the in-sample portfolio returns


    # Setup:
    rows=nrow(yeargrid)

    benchmarkreturns = as.vector(benchmarkreturns)

    # Function:
    for (rnum in 2:rows) {
        insample    = yeargrid[rnum-1,]
        outofsample = yeargrid[rnum,]
        infrom      = insample [,1]
        into        = insample [,2]
        outfrom     = outofsample [,1]
        outto       = outofsample [,2]
        yearname    = rownames(insample)
        outname     = rownames(outofsample)
        portfoliorows=nrow(portfolioreturns[[yearname]])
        if (cutat<portfoliorows) {
            portfoliorows=cutat
        }

        # print(outname)

        #Check Utility fn for insample , and apply to out of sample row



        # add Equalweighted
        EqualWeighted = 1

        ##################################
        # Risk Reduction utility functions
        # for utility function
        # w' = min(VaR.CornishFisher(p=0.95))
        minmodVaR  = which.min(portfolioreturns[[yearname]][1:portfoliorows,"VaR.CornishFisher.period"])
        #minmodVaRi = which.min(portfolioreturns[[yearname]][1:portfoliorows,"VaR.CornishFisher.inception"])
        minmodVaR3yr  = which.min(portfolioreturns[[yearname]][1:portfoliorows,"VaR.CornishFisher.3yr"])

        # for utility function
        # w' = max(return/VaR.CornishFisher) for both VaR.CornishFisher.period and VaR.CornishFisher.inception
        #SharpeRatio.modified  = which.max(portfolioreturns[[yearname]][1:portfoliorows,"Cumulative.Return"]/portfolioreturns[[yearname]][1:portfoliorows,"VaR.CornishFisher.period"])
        SharpeRatio.modified3yr  = which.max(portfolioreturns[[yearname]][1:portfoliorows,"Cumulative.Return"]/portfolioreturns[[yearname]][1:portfoliorows,"VaR.CornishFisher.3yr"])
        #SharpeRatio.modifiedi = which.max(portfolioreturns[[yearname]][1:portfoliorows,"Cumulative.Return"]/portfolioreturns[[yearname]][1:portfoliorows,"VaR.CornishFisher.inception"])

        # for utility function
        # w' = max(return/Max.Drawdown)
        ReturnOverDrawdown = which.max(portfolioreturns[[yearname]][1:portfoliorows,"Cumulative.Return"]/portfolioreturns[[yearname]][1:portfoliorows,"Max.Drawdown"])

        # for utility function
        # w' = max(return)
        maxReturn = which.max(portfolioreturns[[yearname]][1:portfoliorows,"Cumulative.Return"])

        # for utility function
        # w' = min(VaR.CornishFisher(p=0.95)) such that return is greater than the benchmark
        minVaRretoverBM = which.min(portfolioreturns[[yearname]][which(portfolioreturns[[yearname]][1:portfoliorows,"Cumulative.Return"]>=Return.cumulative(benchmarkreturns[infrom:into])),"VaR.CornishFisher.period"])
        if (length(minVaRretoverBM)==0) { minVaRretoverBM = maxReturn }

        #for utility function
        #w' = max(return) such that VaR.CornishFisher is less than VaR.CornishFisher(benchmark)
        maxmodVaRltBM=which.max(portfolioreturns[[yearname]][which(portfolioreturns[[yearname]][1:portfoliorows,"VaR.CornishFisher.period"]<VaR.CornishFisher(benchmarkreturns[infrom:into],p=0.95)),"Cumulative.Return"])
        if (length(maxmodVaRltBM)==0) { maxmodVaRltBM = 1 }

        #add utility functions tor Equal weighted portfolio
        # for utility function
        # w' = min(VaR.CornishFisher(p=0.95)) such that return is greater than equal weighted portfolio
        minVaRretoverEW = which.min(portfolioreturns[[yearname]][which(portfolioreturns[[yearname]][1:portfoliorows,"Cumulative.Return"]>=portfolioreturns[[yearname]][1,"Cumulative.Return"]),"VaR.CornishFisher.period"])
        if (length(minVaRretoverEW)==0) { minVaRretoverEW = 1 }

        #for utility function
        #w' = max(return) such that VaR.CornishFisher is less than VaR.CornishFisher(equal weighted)
        maxmodVaRltEW=which.max(portfolioreturns[[yearname]][which(portfolioreturns[[yearname]][1:portfoliorows,"VaR.CornishFisher.period"]<portfolioreturns[[yearname]][1,"Cumulative.Return"]),"Cumulative.Return"])
        if (length(maxmodVaRltEW)==0) { maxmodVaRltEW = NA }

        #for utility function
        #w' = max(omega)
        maxOmega = which.max(portfolioreturns[[yearname]][1:portfoliorows,"Omega"])

        #for utility function
        #w' = max(Sharpe.period)
        maxPeriodSharpe = which.max(portfolioreturns[[yearname]][1:portfoliorows,"Sharpe.period"])

        #for utility function
        #w' = max(Sharpe.3.yr)
        max3yrSharpe = which.max(portfolioreturns[[yearname]][1:portfoliorows,"Sharpe.3.yr"])

        #for utility function
        #w' = max(Sharpe.inception)
        #maxInceptionSharpe = which.max(portfolioreturns[[yearname]][1:portfoliorows,"Sharpe.inception"])


        ########## end of utility functions ##########
        # construct a data structure that holds each result for this row
        if (rnum==2) {
                #create data.frame
                result=data.frame()
                resultrow=data.frame()
        }
        # first cbind the columns
        resultrow = cbind(EqualWeighted, minmodVaR, minmodVaR3yr, SharpeRatio.modified3yr, ReturnOverDrawdown, maxReturn,
                           minVaRretoverBM, maxmodVaRltBM, minVaRretoverEW, maxmodVaRltEW,
                           maxPeriodSharpe, max3yrSharpe, maxOmega )

        rownames(resultrow) = outname

        # then rbind the rows
        result    = rbind(result,resultrow)
        # print(resultarray)
    }  # end row loop

    # Result:
    result
}

# ------------------------------------------------------------------------------
BacktestDisplay =
function (R, portfolioreturns, yeargrid, backtestresults, show="Cumulative.Return", benchmarkreturns )
{ # a function by Brian G. Peterson

    # Description:
    # This function lets us use the output of the Backtest() function to do some
    # comparative analysis of how each utility function performed out of sample.
    # It takes as input all the component parts, and shows a single summary statistic
    # for each out of sample period for each utility function.  Periods are rows,
    # utility functions are columns in the output.
    # Eventually, we'll want to make this more sophisticated, and return a
    # data structure with *all* the summary statistics for each out-of-sample portfolio,
    # but this works for now.
    #
    # R                 data frame of historical returns
    #
    # portfolioreturns  list of data frames of set of returns for all possible portfolios
    #                   (output of BruteForcePortfolios function)
    #
    # yeargrid          list of from/to vectors for the periods we've run the backtest over
    #                   yeargrid will have one row for the last out of sample year,
    #                   which is not calculated by BruteForcePortfolios
    #
    # backtestresults   data frame of set of weighting vectors for each
    #                   utility function in each year/period
    #                   (output of Backtest function)
    #
    # show              column name to display from portfolioreturns row
    #                   corresponding to weighting vector
    #
    # benchmarkreturns  return vector for benchmark, should match the dates on
    #                   the in-sample portfolio returns

    # Setup:
    rows=nrow(yeargrid)-1  #hack to deal with incomplete data in current year

    benchmarkreturns = as.vector(benchmarkreturns)

    # Function:
    for (rnum in 1:rows) {
        yearrow   = yeargrid[rnum,]
        from      = yearrow [,1]
        to        = yearrow [,2]
        yearname  = rownames(yearrow)

        # construct a data structure that holds each result for this row
        if (rnum==1) {
                #create data.frame
                result=data.frame()
                resultrow=data.frame()
        }
        #if(rnum==rows){return}

        # now build our results
        Benchmark     = Return.cumulative (benchmarkreturns[from:to]) #do something spiffy to show the same stats for FoHF index

        # don't need this anymore since we put it in the backtest column grid
        # EqualWeighted = portfolioreturns[[yearname]][1,show]

        #get funky with the backtest array
        backtestrow=t(portfolioreturns[[yearname]][t(backtestresults[yearname,]),show])

        #print(backtestrow)
        colnames(backtestrow)=colnames(backtestresults)

        # first cbind the columns
        resultrow = cbind( Benchmark, backtestrow)

        rownames(resultrow) = yearname

        # then rbind the rows
        result    = rbind(result,resultrow)
        # print(resultarray)

    } # end rows loop

    #Result:
    result

}

# ------------------------------------------------------------------------------
BacktestWeightDisplay =
function(backtestresults, yeargrid, weightgrid, R)
{ # @author Brian G. Peterson

    # Description:
    # Display the weights chosen for each year/period for each utility function.
    #
    # backtestresults   data frame of set of weighting vectors for each
    #                   utility function in each year/period
    #                   (output of Backtest function)
    #
    # yeargrid          list of from/to vectors for the periods we've run the backtest over
    #                   yeargrid will have one row for the last out of sample year,
    #                   which is not calculated by BruteForcePortfolios
    #
    # weightgrid        each row contains one weighting vector, same number of columns as your returns
    #
    # R                 data frame of historical returns
    #
    # Return:
    # list of years/periods with each period containing a data frame of weights by utiltiy function

    # Setup:
    rows=nrow(yeargrid)-1 # take out the first in-sample year

    cols = ncol(backtestresults) # get the number of utility functions
    componentnames = colnames(R)
    utilitynames   = colnames (backtestresults)

    # Function:
    # first loop on out of sample years/periods
    for (rnum in 2:rows) {
        row = yeargrid[rnum,]
        yearname=rownames(row)
        # print(yearname)
        if (rnum==2) {
            #create empty list, as c() doesn't work the way you would expect with a list
            result=vector("list")
        }

        # now loop on all the utility functions
        for (col in 1:cols) {
            weightingvectornum = backtestresults[rnum,col]
            #print (weightingvectornum)
            weightingvector    = weightgrid[weightingvectornum,]
            print (weightingvector)
            utilityname=colnames(backtestresults[rnum,col])
            print (utilityname)
            utilityrow = c(t(weightingvector),utilityname)
            #rownames(utilityrow)=rownames(weightingvector)
            #print(utilityrow)
            if (col==1){
                currentyeardata=data.frame(utilityrow=utilityrow)
            } else {
                currentyeardata=rbind(currentyeardata,utilityrow)
            }
        } # end utility functions loop

        colnames(currentyeardata)=c(componentnames,"Utility Function")
        #assign each year into the list using the yearname as the index
        result[[yearname]]=currentyeardata

    } # end years/periods loop
    names(result) = t(rownames(yeargrid[2:rows,]))

    #Return:
    result
}


# ------------------------------------------------------------------------------
#MonthlyBacktestResults =
# use pfolioReturn(returnarray,weightingvector) from fPortfolio
MonthlyBacktestResults =
function (R, weightgrid, yeargrid, backtestweights)
{ # @author Brian G. Peterson

    # R                 data structure of component returns
    #
    # weightgrid        each row contains one weighting vector, same number of columns as your returns
    #
    # yeargrid          list of from/to vectors for the periods we want to backtest over
    #
    # backtestweights
    #
    # @returns      data frame where each row has the same index number as a weighting vector,
    #               and each column is one of your metrics from inside this function
    #
    # @example      myreturns=MonthlyBacktestResults(edhec.returns[,1:10], weightingvectors, yeargrid, backtest)

    # Setup:
    rows=nrow(backtestweights)-1
    ##rows=nrow(yeargrid)
    testcols=ncol(backtestweights)
    result=NA

    # data type conditionals
    # cut the return series for from:to
    if (class(R) == "timeSeries") {
        R = R@Data
    } else {
        R = R
    }

    if (ncol(weightgrid) != ncol(R)) stop ("The Weighting Vector and Return Collection do not have the same number of Columns.")


    # Function:
    for(row in 1:rows) {
        yearname  = rownames(backtestweights[row,])
        yearrow   = yeargrid[yearname,]
        from      = yeargrid [yearname,1]
        to        = yeargrid [yearname,2]

        # ok, we're looping on year.
        # for each year, we need to apply the weights in our backtest results to the portfolio and get a monthly return

        for (col in 1:testcols) {

            w = as.numeric(weightgrid[backtestweights[row,col],])

            # pfolioReturn
            colreturn=pfolioReturn(R[from:to,],w)

            if (col==1) {
                # add the edhec returns
                # edhec = NA

                # add the equal weighted portfolios
                equalweight = pfolioReturn(R[from:to,],as.numeric(weightgrid[1,]))
                #colnames(equalweight)="EqualWeighted"

                #create data.frame
                resultcol=data.frame(Value=equalweight)
            }

            mycol=data.frame(Value=colreturn)
            resultcol=cbind(resultcol,mycol)

        }
        colnames(resultcol)=c("EqualWeighted",colnames(backtestweights))
        if (row==1) {
                #create data.frame
                result=data.frame(resultcol)
        } else {
            resultrow = data.frame(resultcol)
            result    = rbind(result,resultrow)
        }

    } #end rows loop

    # set pretty labels for things eventually

    # Return Value:
    result

}


# ------------------------------------------------------------------------------
# GeometricReturn
# use Return.annualized or Return.cumulative from Peter Carl in performance-analytics.R

###############################################################################
# $Log: not supported by cvs2svn $
# Revision 1.37  2008/01/20 17:08:24  kris
# Compute SR more efficiently
#
# Revision 1.36  2008/01/20 16:30:50  brian
# - move multivariate moment calculations outside the row loop
#
# Revision 1.35  2008/01/20 16:26:21  brian
# - add M3 and M4 moments to parameters for all modSR function calls
#
# Revision 1.34  2008/01/20 16:14:53  brian
# - initialize result outside the loop in WeightedReturns
# - initialize resultrow to have one row
#
# Revision 1.33  2008/01/20 14:54:55  brian
# - quote methods
#
# Revision 1.32  2008/01/20 14:53:05  brian
# - fix syntax errors and handling of inception, threeyr, form, to
#
# Revision 1.31  2008/01/20 13:55:44  brian
# - fix syntax error in switch on InceptionStdDev (missing comma)
#
# Revision 1.30  2008/01/20 13:49:39  brian
# - add Kris to copyright line
#
# Revision 1.29  2008/01/20 13:48:37  brian
# - fix syntax error
# - update methods to reflect changes to multivariate moments
#
# Revision 1.28  2008/01/20 13:35:34  brian
# - add missing brace in switch statement
#
# Revision 1.27  2008/01/20 12:07:24  kris
# - Changed function definitions in optim_functions.R and updated the function calls in optimizer.R to these functions
#
# Revision 1.26  2008/01/20 06:23:12  brian
# - convert GVaR functions
#
# Revision 1.25  2008/01/20 05:02:17  brian
# - add in centered moments and standard variables for period, inception, and 3yr series
#
# Revision 1.24  2008/01/19 16:48:01  brian
# - fix column name issues
# - add period, inception, and 3yr for each method
#
# Revision 1.23  2008/01/05 04:49:25  brian
# - add 'methods' argument to parameterize WeightedReturns and BrutForcePortfolios functions
# - not yet tested, may have issues with column names
#
# Revision 1.22  2008/01/04 14:27:07  brian
# - convert to use functions from package PerformanceAnalytics
#
# Revision 1.21  2007/01/31 18:23:16  brian
# - cascade function name standardization from performance-analytics.R
#
# Revision 1.20  2007/01/30 15:54:57  brian
# - cascade function name standardization from extra_moments.R
#
# Revision 1.19  2007/01/26 13:24:02  brian
# - fix typo
#
# Revision 1.18  2006/12/03 17:42:02  brian
# - adjust utility functions in Backtest() to match 3yr statistices from BruteForcePortfolios
# - add more descriptive comments to BacktestDisplay()
# - add BacktestWeightDisplay() fn, not yet complete
# Bug 840
#
# Revision 1.17  2006/12/02 12:54:53  brian
# - modify BacktestData() fn to take a 'yeargrid' that matches
#    yeargrid from BruteForcePortfolios and loads those portfolios
# Bug 840
#
# Revision 1.16  2006/11/30 00:24:11  brian
# - remove 'inception' statistics from BruteForcePortfolios and Backtest fns
# - fix error in 'show' parameter of BacktestDisplay fn
# Bug 840
#
# Revision 1.15  2006/11/28 02:52:03  brian
# - add 3yr SharpeRatio.modified and 3yr modVaR
# - add fOptions require for Omega
# Bug 840
#
# Revision 1.14  2006/10/12 17:42:48  brian
# - put back omega utility fn
#
# Revision 1.13  2006/09/26 23:42:53  brian
# - add Equalweighted as column in Backtest vector fns
# - clean up NA handling in utility functions
# - add more error handling
#
# Revision 1.12  2006/09/26 21:53:41  brian
# - more fixes for NA's in data
#
# Revision 1.11  2006/09/26 12:07:04  brian
#  - add more NA handlinf and data series size checks
#  - comment out Omega for speed for now
#
# Revision 1.10  2006/09/22 15:30:44  brian
# - add separate vector to BacktestDisplay fn for benchmark returns
#
# Revision 1.9  2006/09/22 12:45:45  brian
# - add separate vector for benckmarkreturns to Backtest fn
# - better describe inputs to Backtest fn in comments
#
# Revision 1.8  2006/09/21 13:43:39  brian
# - add start timestamp for Backtest function
#
# Revision 1.7  2006/09/12 14:37:43  brian
# - add CVS tags
# - add CVS log
# - add confidentiality notice to top of file
#
# Revision 1.6 2006-09-12 09:31:37 brian
# - snapshot 2006-09-05 15:36
# - add functions and tweak existing to better handle larger data sets, cutting data
#
# Revision 1.5 2006-09-12 09:29:12 brian
# - snapshot 2006-08-30 19:03
# - add functions for conthly compounding returns
#
# Revision 1.4 2006-09-12 09:28:01 brian
# - snapshot 2006-08-29 23:01
# - add equal weighted utility functions
#
# Revision 1.3 2006-09-12 09:27:00 brian
# - snapshot 2006-08-29 21:58
# - Add functions to actually perform the backtest
#   using the results of the brute force statistics
#   generated on all possible portfolios.
#
# Revision 1.2 2006-09-12 09:25:06 brian
# - snapshot 2006-08-29
# - add BruteForcePortfolios, WeightedReturns, and other small utility functions
#
# Revision 1.1 2006-09-12 09:23:14 brian
# - initial revision 2006-08-28
# Bug 840
###############################################################################
